spring.application.name=chat-app-backend
# use MONGO_URI from Render env
spring.mongodb.uri=mongodb://localhost:27017/chatapp
# Render provides PORT, fallback to 8080
spring.data.mongodb.auto-index-creation=true
spring.ai.openai.api-key=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
spring.ai.openai.chat.model=openai/gpt-oss-120b:free
spring.ai.openai.base-url=https://openrouter.ai/api