spring.application.name=chat-app-backend
# use MONGO_URI from Render env
spring.mongodb.uri=mongodb://localhost:27017/chatapp
# Render provides PORT, fallback to 8080
spring.data.mongodb.auto-index-creation=true
spring.ai.openai.api-key=<GROQ_API_KEY>
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile